name: Tommaso
aboutMe: "*To see my current project and interests, visit [my Github Readme](https://github.com/heytdep)*.<br /> Hi, my name is Tommaso. I am a Developer from Italy 🇮🇹. I like programming anything that has an integration with a WebApp and I have a big interest in Deep Learning. Also, I am currently building on Cryptos."
bio: Developer • Deep Learning Enthusiast • Building with/on/for Blockchain
blog: "I am constantly writing new programming and tech-related articles on my Medium blog. Also, I've just reached 100K total views 🎯, thank you!. This is a static website, however, to keep you posted I created this medium page with all my updated articles: [my blog](https://tdpdev.medium.com/links-and-useful-resources-16534e26df0f)"
acknowledgments: I sometimes do bug bounties, mainly on Hackerone. These are the Acknowledgments I have received for my research:Google, Wickr, BitPanda, BBC, Dashlane. UIPath, Acronis, Basecamp, Valve, Via, Courier, Aiven, VMware, Slack
mediumHandle: tdep
hackeroneHandle: hensis
githubHandle: heytdep
bioimg: mediumphotoprofile.jpg
