name: Tommaso
aboutMe: Hi, my name is Tommaso. I am a Developer from Italy 🇮🇹. I like programming anything that has an integration with a WebApp and I have a big interest in Deep Learning. Also, I am currently building on Cryptos.
bio: Developer • Deep Learning Enthusiast&nbsp;• Building with and on Cryptos
blog: I am constantly writing new programming and tech-related articles on my Medium blog. This is a static website, however, to keep you posted I created this medium page with all my updated articles: https://tdpdev.medium.com/links-and-useful-resources-16534e26df0f
acknowledgments: I sometimes do bug bounties, mainly on Hackerone. These are the Acknowledgments I have received for my research:Google, Wickr, BitPanda, BBC, Dashlane. UIPath, Acronis, Basecamp, Valve, Via, Courier, Aiven, VMware, Slack
mediumHandle: tdpdev
hackeroneHandle: hensis
githubHandle: hensis
bioimg: profimg.jpeg
